version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12.0
    working_directory: ~/project/sdk
    steps:
      - checkout
      # Setting up a virtual environment for the Python project
      - run: python3 -m venv .env
      - run: source .env/bin/activate
      # Install Rust
      - run: 
          name: Install Rust
          command: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            echo 'source $HOME/.cargo/env' >> $BASH_ENV
            source $BASH_ENV
      - run: rustc --version # just to confirm it's installed
      # Install maturin and dependencies
      - run:
          name: Activate virtualenv and install dependencies
          command: |
            . .env/bin/activate
            pip install maturin[patchelf]
      - run:
          name: Build and develop the package
          command: |
            . .env/bin/activate
            cd sdk
            maturin develop
      # Run the unittests
      - run:
          name: Run tests
          command: |
            . .env/bin/activate
            cd sdk
            python3 test.py

workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - build-and-test
