[package]
name = "aleo_python_sdk"
authors = ["Konstantin Pandl", "Mike Turner"]
version = "0.0.1"
edition = "2021"

[dependencies]
rand = { version = "^0.8" }
pyo3 = { version = "0.18.2", features = ["extension-module"] }
snarkvm = { version = "0.12.6", features = ["console"] }