[package]
name = "aleo"
authors = ["Konstantin Pandl", "Mike Turner"]
version = "0.0.3"
description = "A Python sdk for zero-knowledge cryptography based on Aleo"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
rand = { version = "^0.8" }
pyo3 = { version = "0.18.2", features = ["extension-module"] }
snarkvm = { version = "0.12.6", features = ["console"] }