name: SDK

on:
  workflow_call:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdk
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: fmt
        run: cargo fmt --check
      - name: clippy
        run: cargo clippy -- -D warnings
      - uses: jordemort/action-pyright@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: ./sdk
          fail_on_error: true
  build_test:
    name: Build & Test
    needs: [check]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdk
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Build
        uses: PyO3/maturin-action@v1
        with:
          args: --release --features openssl/vendored
          working-directory: ./sdk
      - name: Install Wheel
        run: pip install target/wheels/*.whl
      - name: Build & Test RTD
        run: |
          pip install -r docs/requirements.txt
          sphinx-build docs/source/ _readthedocs/
          sphinx-build -b doctest docs/source/ _readthedocs/doctest
      - name: Test
        run: |
          python -m venv .env
          source .env/bin/activate
          maturin develop --release --features openssl/vendored
          python python/test.py
